name: Workflow Initialize
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
outputs:
  telemetryScopeJson:
    description: A telemetryScope that covers the workflow
    value: ${{ steps.workflowinitialize.outputs.telemetryScopeJson }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: workflowinitialize
      run: |
        $algoAction = [scriptblock] { 
          ${{ github.action_path }}/WorkflowInitialize.ps1
        }

        # Run the script block
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -Action $algoAction
branding:
  icon: terminal
  color: blue
