name: Analyze Tests
author: Microsoft Corporation
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  project:
    description: Project to analyze
    required: true
outputs:
  TestResultMD:
    description: MarkDown of test result
    value: ${{ steps.AnalyzeTests.outputs.TestResultMD }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: AnalyzeTests
      env:
        _project: ${{ inputs.project }}
      run: |
        ${{ github.action_path }}/../Invoke-AlGoAction.ps1 -Action {
          ${{ github.action_path }}/AnalyzeTests.ps1 -project $ENV:_project
        }
branding:
  icon: terminal
  color: blue
