name: Cleanup Temp Repos

on:
  workflow_dispatch:
    inputs:
      githubOwner:
        description: GitHub organization set as owner for the temp repositories (default is to use your personal account)
        required: false
        default: ''
    workflow_run:
      workflows: [End to end tests]
      types:
        - completed

defaults:
  run:
    shell: pwsh

permissions:
  contents: read

jobs:
  CleanupRepos:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }} # Run only if dispatched or the End to end tests workflow has succeeded
    runs-on: [ ubuntu-latest ]
    name: Cleanup Temp Repos
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Check E2EPAT Secret is defined
        run: |
          if ('${{ Secrets.E2EPAT }}' -eq '') {
            Write-Host "::Error::In order to run end to end tests, you need a Secret called E2EPAT containing a valid Personal Access Token with the following permissions: admin:org, delete_repo, repo, workflow, packages:write"
            exit 1
          }

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get GitHub Owner
        id: getGitHubOwner
        env:
          githubOwner: ${{ github.event.inputs.githubOwner }}
        run: |
          ${{ github.workspace }}/Internal/Scripts/GetOwnerForE2ETests.ps1 -githubOwner $env:githubOwner

      - name: Cleanup Temp Repositories
        env:
          githubOwner: ${{ steps.getGitHubOwner.outputs.githubOwner }}
        run: |
          ${{ github.workspace }}/Internal/Scripts/RemoveTempRepos.ps1 -githubOwner $env:githubOwner -token '${{ Secrets.E2EPAT }}'
